name: Ann Holden
title: Ann Holden
description: >- # this means to ignore newlines until the next yaml key
  A native of Oklahoma City, Ann Holden holds a BA from Smith College, Northampton, MA and an MFA in Painting from the Henry Radford Hope School of Fine Art, Indiana University, Bloomington, IN.
  She also studied at The School of the Art Institute of Chicago, Chautauqua Institute, NY, and has been an Artist-in-Residence at the Vermont Studio Center.
  Prominent teachers include Robert Barnes and Stanley Lewis.
  She was an Assistant Instructor at Indiana University Summer Institute in Florence, Italy, and was Adjunct Professor at Tokai University, Tokyo, Japan.
  Currently, she lives and maintains a studio in Oklahoma City.
descriptions:
  - A native of Oklahoma City, Ann Holden holds a BA from Smith College, Northampton, MA and an MFA in Painting from the Henry Radford Hope School of Fine Art, Indiana University, Bloomington, IN.
  - She also studied at The School of the Art Institute of Chicago, Chautauqua Institute, NY, and has been an Artist-in-Residence at the Vermont Studio Center.
  - Prominent teachers include Robert Barnes and Stanley Lewis.
  - She was an Assistant Instructor at Indiana University Summer Institute in Florence, Italy, and was Adjunct Professor at Tokai University, Tokyo, Japan.
  - Currently, she lives and maintains a studio in Oklahoma City.
email_address: "annholdenparrish@gmail.com"
color: "#212121"
background_color: "#FFFFFF"
logo: "assets/img/logo.png"
apple_mask_icon: "assets/img/apple-mask-icon.svg"
themed_mask_icon: "assets/img/themed-mask-icon.png"
sharing_image: "assets/img/share.jpg"
