name: Ann Holden
title: Ann Holden
description: >- # this means to ignore newlines until the next yaml key
  Works from the artist Ann Holden.
color: "#212121"
background_color: "#FFFFFF"
logo: "assets/img/logo.png"
apple_mask_icon: "assets/img/apple-mask-icon.svg"
themed_mask_icon: "assets/img/themed-mask-icon.png"
sharing_image: "assets/img/share.jpg"
